defaults: &defaults
  app_name: "TransportServer"
  app_repo_name: "allaboardapps/transport-server"
  app_server: "development"
  brand_name: "TransportServer"
  cta_train_tracker_base_url: "http://lapi.transitchicago.com/api/1.0/ttarrivals.aspx"
  default_url: "http://localhost:3000"
  google_analytics_tracking_id: "UA-xxxxxx-x"
  support_email: "support@allaboardapps.com"

test:
  <<: *defaults
  app_server: "test"
  google_analytics_tracking_id: "UA-xxxxxx-x"

development:
  <<: *defaults
  google_analytics_tracking_id: "UA-xxxxxx-x"

staging:
  <<: *defaults
  app_server: "staging"
  default_url: "https://transport-server-staging.herokuapp.com"
  google_analytics_tracking_id: "UA-xxxxxx-x"

production:
  <<: *defaults
  app_server: "production"
  default_url: "https://transport-server-production.herokuapp.com"
  google_analytics_tracking_id: "UA-xxxxxx-x"
